### PR TITLE
Various fixes and improvements

### LINKED ISSUE #10: Should not allow non-sound files to be dropped

### LINKED ISSUE #11: Closing the window while the timer is running hangs

### LINKED ISSUE #12: The elapsed time should be displayed in h:mm:ss format
The format should always have 2 digits each for minutes and seconds, e.g., 0:00:09 and 10:09:00, etc.

### LINKED ISSUE #13: The window title doesn't reset after the timer is stopped

### PR DESCRIPTION
**Pull request by R4H33M**
Sorry for the multi-issue PR. I can re-do them into seperate PRs if you would wish, but since they are all small fixes, I figured they could just go into one. Fixes the following issues:

Fixes #10 
Fixes #12 
Fixes #13 
Tested on x86 and x86_64.

### CODE REVIEW

File: buzzwindow.cpp [hunk 1]
```diff
@@ -73,11 +74,19 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
 				{
-					MyClock->SetSound(new BFileGameSound(&ref, false));
-					SoundName->SetText(ref.name);
+					if (BFileGameSound(&ref, false).InitCheck() == B_OK) {
+						MyClock->SetSound(new BFileGameSound(&ref, false));
+						SoundName->SetText(ref.name);
+					} else {
+						BAlert* not_supported = new BAlert(
+							"Error",
+							"The file placed could not be loaded.",
```
Comment (humdingerb) [inline buzzwindow.cpp]: Maybe better:
> This is not a supported sound file.

File: buzzwindow.cpp [hunk 2]
```diff
@@ -91,6 +100,7 @@ void BuzzWindow::MessageReceived(BMessage* message)
 			if(Playing)
 			{
 				Playing = false;
+				SetTitle("WakeUp v1.0");
```
Comment (humdingerb) [inline buzzwindow.cpp]: Let's remove the version info from the title.

File: buzzwindow.cpp [hunk 3]
```diff
@@ -137,7 +147,18 @@ int32 TimerThread(void *data)
 		snooze(1000000);
 		T->AddTime(1000000); //+1 sec
 		TimeString = "";
-		TimeString << ((uint32)T->GetHour()) << ":" << ((uint32)T->GetMinute()) << ":" << ((uint32)T->GetSecond());
+		//h:mm:ss format
+		TimeString << ((uint32)T->GetHour()) << ":";
+		if (T->GetMinute() > 9) {
```
Comment (humdingerb) [inline buzzwindow.cpp]: The curly brackets here nd below aren't needed. Removing them makes the code appear simpler IMO.

File: buzzwindow.cpp [hunk 4]
```diff
@@ -73,11 +74,19 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
+							"Error",
+							"The file placed could not be loaded.",
+							"OK", NULL, NULL, B_WIDTH_AS_USUAL,
+							B_OFFSET_SPACING, B_WARNING_ALERT);
+						not_supported->Go();
+					}
 				}
 			}
-   		
    			else BWindow::MessageReceived(message);break;
```
Comment (humdingerb) [inline buzzwindow.cpp]: This "break" can be removed.

**Review by humdingerb — CHANGES_REQUESTED** [review]
It's still also crashing here:
* Open WakeUp
* Drop a sound file
* Start the clock
* Quit the app

Crash report: https://linx.li/wakeup-66385-debug-13-01-2020-15-57-09.report

**Comment by R4H33M** [comment]
I've made the suggested fixes. 
I'll look more into the bug, but from first glance, it seems to be caused by the issues I described above:

>the clock thread is stopped automatically when a "Quit Requested" is sent - even without escaping the loop by setting Playing = false.

So, I think this is something we need to fix in Haiku's code base...

File: buzzwindow.cpp [hunk 5]
```diff
@@ -1,3 +1,4 @@
+#include <Alert.h>
 #include "buzzwindow.h"
```
Comment (owenca) [inline buzzwindow.cpp]: Swap these two lines.

File: buzzwindow.cpp [hunk 6]
```diff
@@ -54,7 +56,6 @@ bool BuzzWindow::QuitRequested()
 {
 	Playing = false;
 	status_t* exitvalue=NULL;
-	wait_for_thread(ClockId, exitvalue); //wait for the clock thread to finishes
```
Comment (owenca) [inline buzzwindow.cpp:57]: Let's fix this in a separate pull request.

File: buzzwindow.cpp [hunk 7]
```diff
@@ -73,11 +74,19 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
+							"Error",
+							"This is not a supported sound file.",
+							"OK", NULL, NULL, B_WIDTH_AS_USUAL,
+							B_OFFSET_SPACING, B_WARNING_ALERT);
+						not_supported->Go();
+					}
 				}
 			}
-   		
    			else BWindow::MessageReceived(message);break;
```
Comment (owenca) [inline buzzwindow.cpp]: This is a good opportunity to rework the logic in this `case` statement (lines 69-90).

File: buzzwindow.cpp [hunk 8]
```diff
@@ -115,7 +125,7 @@ void BuzzWindow::MessageReceived(BMessage* message)
    			}
    		}
    		
-   		default:BWindow::MessageReceived(message);break;
+		default:BWindow::MessageReceived(message);
```
Comment (owenca) [inline buzzwindow.cpp]:
```suggestion
		default:
			BWindow::MessageReceived(message);
```

File: buzzwindow.cpp [hunk 9]
```diff
@@ -137,7 +147,16 @@ int32 TimerThread(void *data)
 		snooze(1000000);
 		T->AddTime(1000000); //+1 sec
 		TimeString = "";
-		TimeString << ((uint32)T->GetHour()) << ":" << ((uint32)T->GetMinute()) << ":" << ((uint32)T->GetSecond());
+		//h:mm:ss format
+		TimeString << ((uint32)T->GetHour()) << ":";
```
Comment (owenca) [inline buzzwindow.cpp]:
```suggestion
		TimeString << T->GetHour() << ":";
```

File: buzzwindow.cpp [hunk 10]
```diff
@@ -137,7 +147,16 @@ int32 TimerThread(void *data)
...
+		if (T->GetMinute() > 9)
+			TimeString << ((uint32)T->GetMinute()) << ":";
+		else
+			TimeString << "0" << ((uint32)T->GetMinute()) << ":";
```
Comment (owenca) [inline buzzwindow.cpp]:
```
		int t = T->GetMinute();
		if (t < 10)
			TimeString << "0";
		TimeString << t << ":";
```

File: buzzwindow.cpp [hunk 11]
```diff
@@ -137,7 +147,16 @@ int32 TimerThread(void *data)
...
+		if (T->GetSecond() > 9)
+			TimeString << ((uint32)T->GetSecond());
+		else
+			TimeString << "0" << ((uint32)T->GetSecond());
```
Comment (owenca) [inline buzzwindow.cpp]:
```
		t = T->GetSecond();
		...
```

**Review by owenca — CHANGES_REQUESTED** [review]

**Comment by humdingerb** [comment]
If the countdown thread keeps acting up, using a BMessageRunner might be a better solution.

**Comment by owenca** [comment]
Or use `BStringView::Pulse()`. See [here](https://github.com/HaikuArchives/BeVexed/blob/master/source/TimerView.cpp) for an example.

**Comment by R4H33M** [comment]
> If the countdown thread keeps acting up, using a BMessageRunner might be a better solution.
> Or use BStringView::Pulse(). See here for an example.

I'll investigate these two options for fixing issue #11, and make a new PR for what I find works best.

File: buzzwindow.cpp (hunk 7 above)
Comment (R4H33M) [reply buzzwindow.cpp]: How does the logic need to change? It seems to work well...

**Comment by R4H33M** [comment]
Suggestions have been implemented. Code looks nicer now, thanks!
As this is not providing a fix for #11 anymore, I have edited the PR message on top, so issue #11 will not close if this PR is merged.

File: buzzwindow.cpp (hunk 7 above)
Comment (korli) [reply buzzwindow.cpp]: BFileGameSound is instanciated twice.

File: buzzwindow.cpp (hunk 6 above)
Comment (korli) [reply buzzwindow.cpp:57]: the comment should stay, yes?

File: buzzwindow.cpp [hunk 12]
```diff
@@ -115,7 +126,8 @@ void BuzzWindow::MessageReceived(BMessage* message)
    			}
    		}
    		
-   		default:BWindow::MessageReceived(message);break;
+		default:
+			BWindow::MessageReceived(message);
```
Comment (korli) [inline buzzwindow.cpp:126]: Why removes break; here?

File: buzzwindow.cpp (hunk 7 above)
Comment (R4H33M) [reply buzzwindow.cpp]: Fixed.

**Comment by R4H33M** [comment]
New commits pushed.

File: buzzwindow.cpp (hunk 7 above)
Comment (owenca) [reply buzzwindow.cpp]: > How does the logic need to change? It seems to work well...

Writing efficient, self-explanatory (whenever possible), and robust code is much more than "It seems to work well..." :)

In addition to the problem that `BFileGameSound` was instantiated twice (as @korli pointed out), the if-statement `if((Entry.GetRef(&ref) == B_OK))` is superfluous because `Entry` was just initialized from `ref` without symlink traversing. Also, the local variable `path` was not used in the `case` block and thus should be removed. Finally, the nested if-else statements are unnecessarily deep.

So you can do something like the following:
```
			entry_ref ref;
			if (message->FindRef("refs", &ref) != B_OK) {
				BWindow::MessageReceived(message);
				break;
			}

			BFileGameSound soundFile(&ref, false);
				// The above line is wrong. Use pointer/new instead.
			if (soundFile.InitCheck() != B_OK) {
				BAlert* alert = new BAlert("Error",
					"This is not a supported sound file.", "OK");
				alert->SetType(B_WARNING_ALERT);
				alert->Go();
				break;
			}

			MyClock->SetSound(&soundFile);
			SoundName->SetText(ref.name);
```

File: buzzwindow.cpp [hunk 13]
```diff
@@ -67,18 +69,26 @@ void BuzzWindow::MessageReceived(BMessage* message)
    		{// Look for a ref in the message
 		   	entry_ref ref;
 			BPath path;
```
Comment (owenca) [inline buzzwindow.cpp]:
```suggestion
```

File: buzzwindow.cpp [hunk 14]
```diff
@@ -67,18 +69,26 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
-   			if(message->FindRef("refs", &ref) == B_OK)
-   			{
+			if(message->FindRef("refs", &ref) == B_OK) {
 				BEntry Entry(&ref);
 				Entry.GetPath(&path);
 				if((Entry.GetRef(&ref) == B_OK))
 				{
```
Comment (owenca) [inline buzzwindow.cpp]: Delete them.

File: buzzwindow.cpp [hunk 15]
```diff
@@ -67,18 +69,26 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
-					MyClock->SetSound(new BFileGameSound(&ref, false));
-					SoundName->SetText(ref.name);
+					BFileGameSound soundFile(&ref, false);
```
Comment (owenca) [inline buzzwindow.cpp]: Crashes when dropping a second supported file. Use pointer/new instead.

File: buzzwindow.cpp [hunk 16]
```diff
@@ -67,18 +69,26 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
+					if (soundFile.InitCheck() == B_OK) {
+						MyClock->SetSound(&soundFile);
+						SoundName->SetText(ref.name);
+					} else {
+						BAlert* not_supported = new BAlert(
+							"Error",
+							"This is not a supported sound file.",
+							"OK", NULL, NULL, B_WIDTH_AS_USUAL,
+							B_OFFSET_SPACING, B_WARNING_ALERT);
```
Comment (owenca) [inline buzzwindow.cpp]:
```
						BAlert* not_supported = new BAlert("Error",
							"This is not a supported sound file.", "OK");
						not_supported->SetType(B_WARNING_ALERT);
```

File: buzzwindow.cpp [hunk 17]
```diff
@@ -67,18 +69,26 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
+						not_supported->Go();
+					}
 				}
```
Comment (owenca) [inline buzzwindow.cpp]: Delete it.

**Review by owenca — CHANGES_REQUESTED** [review]

File: buzzwindow.cpp (hunk 17 above)
Comment (owenca) [reply buzzwindow.cpp]: I prefer [this](https://github.com/HaikuArchives/WakeUp/pull/14#discussion_r366681410) to the above though.

File: buzzwindow.cpp (hunk 7 above)
Comment (R4H33M) [reply buzzwindow.cpp]: Thank you for your explanation. I am still finding my way around C++, and I am training my eye to judge between bad and good code. I've reworked the logic as suggested.

File: buzzwindow.cpp [hunk 18]
```diff
@@ -66,19 +68,22 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
+			if(message->FindRef("refs", &ref) != B_OK) {
+				BWindow::MessageReceived(message);
+				break;
 			}
-   		
-   			else BWindow::MessageReceived(message);break;
+
+			BFileGameSound* soundFile = new BFileGameSound(&ref, false);
+			if (soundFile->InitCheck() != B_OK) {
+				BAlert* not_supported = new BAlert("Error",
```
Comment (owenca) [inline buzzwindow.cpp:79]:
```suggestion
				delete soundFile;
				BAlert* not_supported = new BAlert("Error",
```

**Review by owenca — CHANGES_REQUESTED** [review]
Fix the memory leak, and then we are all set.

File: buzzwindow.cpp [hunk 19]
```diff
@@ -66,19 +68,23 @@ void BuzzWindow::MessageReceived(BMessage* message)
...
-   			if(message->FindRef("refs", &ref) == B_OK)
-   			{
-				BEntry Entry(&ref);
-				Entry.GetPath(&path);
-				if((Entry.GetRef(&ref) == B_OK))
-				{
-					MyClock->SetSound(new BFileGameSound(&ref, false));
-					SoundName->SetText(ref.name);
-				}
+			if(message->FindRef("refs", &ref) != B_OK) {
```
Comment (owenca) [inline buzzwindow.cpp]:
```suggestion
			if (message->FindRef("refs", &ref) != B_OK) {
```

**Review by owenca — CHANGES_REQUESTED** [review]
Please also update WakeUp.png with a new screenshot.

**Comment by owenca** [comment]
And squash the commits.

**Comment by R4H33M** [comment]
Done :)
Thanks for all your support!! @owenca @humdingerb @korli

**Review by owenca — APPROVED** [review]
